service: lambda-test-sanghwa

configValidationMode: error

# layers:
#   lambda-test-sanghwa-dev:
#     path: layer
#     compatibleRuntimes:
#       - nodejs18.x

provider:
  name: aws
  stage: dev
  runtime: nodejs18.x
  region: ap-northeast-2
  profile: loomex-dev
  memorySize: 1024
  timeout: 300

plugins:
  - serverless-offline

functions:
  api:
    handler: ./lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
    layers:
      - arn:aws:lambda:ap-northeast-2:972521143148:layer:ffmpeg:3
    environment:
      
  
package:
  patterns:
    - "!node_modules/**"
